name: E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup database (for local testing)
        run: |
          # Using SQLite for CI environment
          echo "DATABASE_URL=file:./test.db" > .env.local
          echo "NEXTAUTH_SECRET=test-secret" >> .env.local
          echo "NEXTAUTH_URL=http://localhost:3000" >> .env.local
          npm run prisma:generate
          
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        
      - name: Setup test directories
        run: |
          mkdir -p e2e/.auth
          
      - name: Run Playwright tests
        run: npm run test:e2e:ci
        env:
          CI: true
          NODE_ENV: test
        
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
